exclude: |
  (?x)^(analyses/)
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.13
    hooks:
      - id: ruff-check
        args: [--fix, "--select=B,C4,F,I,PIE,RUF,SIM,UP,W"]
      - id: ruff-format
  - repo: https://github.com/seddonym/import-linter
    rev: v2.11
    hooks:
      - id: import-linter
        language: python
  # Run mypy within the venv so that libraries are visible
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: uv run mypy jdluc validation
        pass_filenames: false
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.26
    hooks:
      - id: uv-lock
  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
        entry: mdformat --number --wrap=no
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace
